name: Audits

on:
  pull_request:
  push:
    branches: master

permissions:
  contents: read

jobs:
  cargo-vet:
    name: Vet Rust dependencies
    runs-on: tenki-standard-large-plus-16c-32g
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        id: toolchain
      - run: rustup override set ${{steps.toolchain.outputs.name}}
      - run: cargo install cargo-vet --version ~0.10
      - run: cargo vet --locked

  cargo-deny:
    name: Check licenses
    runs-on: tenki-standard-large-plus-16c-32g
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check licenses
